name: file2text
description: File to text Converter
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  share: ^0.6.3+6
  toast: ^0.1.5
  gallery_saver: ^1.0.7
  url_launcher: ^5.4.2
  progress_dialog: ^1.2.2
  connectivity: ^0.4.8+2
  image_gallery: ^1.2.0
  clipboard_manager: ^0.0.1
  shared_preferences: ^0.5.6+3
  splashscreen: ^1.2.0
  dio: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  image_cropper:
  fancy_bottom_navigation:
  flutter_launcher_icons:
  multi_image_picker:
  image_picker:
  file_picker:

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
